chore: Update dependencies and clean up eslint.
thenativeweb/wolkenkit pull request #1503
Opened 2020-10-30 17:59 UTC by yeldiRium

2020-11-02 07:30 UTC, goloroden requested changes
Hey @yeldiRium @grundhoeferj 👋 

Thanks for the PR, I've reviewed it (quickly), and found a few things, where I at least have questions. Can you maybe have a second look?

2020-11-02 07:30 UTC, goloroden commented on lib/common/utils/path/getAbsolutePath.ts
> +// eslint-disable-next-line unicorn/import-style
Is there a special reason why it is preferable here to disable the linter instead of fixing the problem?

2020-11-02 07:30 UTC, goloroden commented on lib/messaging/pubSub/Publisher.ts
> +// eslint-disable-next-line @typescript-eslint/ban-types
This disabling isn't needed any more, is it? We should probably search for `ban-types` and check whether there are more than that where it can be removed.

2020-11-02 07:30 UTC, goloroden commented on lib/stores/domainEventStore/MongoDb/MongoDbDomainEventStore.ts
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
Why is this needed?

2020-11-02 07:36 UTC, yeldiRium commented on lib/common/utils/path/getAbsolutePath.ts
> +// eslint-disable-next-line unicorn/import-style
yes: the function `getAbsolutePath` below takes a parameter called `path`, so wa can't use that name to import the `path` module here.

2020-11-02 07:37 UTC, yeldiRium commented on lib/stores/domainEventStore/MongoDb/MongoDbDomainEventStore.ts
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
Iirc it should not be needed anymore. I'll double check.

2020-11-02 07:37 UTC, yeldiRium commented on lib/messaging/pubSub/Publisher.ts
> +// eslint-disable-next-line @typescript-eslint/ban-types
Agreed.

2020-11-02 07:37 UTC, goloroden commented on lib/common/utils/path/getAbsolutePath.ts
> +// eslint-disable-next-line unicorn/import-style
Okay 👍

2020-11-02 07:37 UTC, goloroden commented on lib/stores/domainEventStore/MongoDb/MongoDbDomainEventStore.ts
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
Thanks 😊

2020-11-04 08:26 UTC, goloroden commented on lib/messaging/pubSub/Publisher.ts
> +// eslint-disable-next-line @typescript-eslint/ban-types
I fixed this 😊

2020-11-04 08:27 UTC, goloroden approved these changes

2020-11-04 12:49 UTC, merged