Environment variable for heartbeat interval
thenativeweb/wolkenkit pull request #1901
Opened 2021-02-15 14:06 UTC by kusigit

The heartbeat interval should be configurable via an environment variable. The request timeout on the Heroku Cloud is 55 seconds.

https://devcenter.heroku.com/articles/request-timeout#long-polling-and-streaming-responses

The implementation is just for the single process. Maybe we have to adapt it to microservices as well.

2021-02-15 14:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/thenativeweb/wolkenkit?pullRequest=1901) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/thenativeweb/wolkenkit?pullRequest=1901) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/thenativeweb/wolkenkit?pullRequest=1901) it.</sub>

2021-02-18 21:20 UTC, goloroden commented
Hey @kusigit 👋 

Thanks a lot for your PR!
We will have a closer look at it next week, and then get back to you.

Have a nice weekend,


Golo

2021-02-22 10:24 UTC, goloroden commented
@kusigit So, as promised, we get back to you this week 😊

The PR looks pretty good, however, we have two questions on it:

1. Woud you like to add yourself as a contributor to the `package.json` file?
2. Would you mind adding the same settings to the micro-service runtime?

Cheers,


Golo

2021-02-23 08:28 UTC, goloroden requested changes
Hey @kusigit 👋 

Thanks for the quick update, this looks pretty good IMHO 😊 

There is one last thing (see my comment). Would you mind to have another look?

2021-02-23 08:28 UTC, goloroden commented on lib/runtimes/microservice/processes/notification/configurationDefinition.ts
> +    schema: { type: 'integer' }
Should we maybe extract this to a `heartbeatIntervalSchema`, similar to how we did it with ports?

And: Shouldn't we set a `minimum` in that schema, then?

(The same applies to the other places where this parameter is defined.)

2021-02-23 08:54 UTC, goloroden approved these changes

2021-02-23 08:55 UTC, goloroden commented
@kusigit Thanks for the quick update 😊

@yeldiRium To me, this PR looks fine – can you please have another look at it, and (if you are fine with it), merge it?

2021-02-23 08:58 UTC, kusigit commented on lib/runtimes/microservice/processes/notification/configurationDefinition.ts
> +    schema: { type: 'integer' }
Hi @goloroden 
You're right. Good idea. Thanks.

2021-02-23 10:35 UTC, yeldiRium approved these changes

2021-02-23 10:39 UTC, yeldiRium commented
LGTM :+1:

2021-02-23 10:39 UTC, merged