Postgres SSL property
thenativeweb/wolkenkit pull request #2196
Opened 2021-06-16 12:34 UTC by kusigit

The ssl property of the node postgres driver should be an object.

https://node-postgres.com/features/ssl

2021-06-18 08:18 UTC, yeldiRium commented
Hi @kusigit,

thanks for this PR. Sorry for the delay. I finally had some time to take a look at it and have some questions and annotations.

- You extended the JSON schemas to validate certain fields on the `encryptConnection` object. According to the schema, it now has to be an object. According to the `pg` TypeScript types, the `encryptConnection` option is a `boolean | ConnectionOptions`. Is there a reason that you excluded the possible `boolean` type?
- In the schema you listed four properties, `rejectUnauthorized`, `ca`, `key` and `cert`. Is there a reason why you chose these four specifically? The `ConnectionOptions` type has many more properties that we could also allow here, but I don't know what most of them do.
- If we're going to support certain options, we'll need a type for them. Just using `object` as the type for the `encryptConnection` option feels a bit unsafe and we have no TypeScript support when passing these options to the Postgres constructor.
- I also had a look at your PR in `command-line-interface` (https://github.com/thenativeweb/command-line-interface/pull/365) and unfortunately doubt that this approach will work. So far we pass objects to environment variables or CLI options in the form of JSON strings, because I don't see a way to pass an object to a CLI. We should keep this approach and use `string` Options instead, which are then parsed and validated. (See e.g. the `replay` command.) This would make the PR in `command-line-interface` obsolete.

Do you mind elaborating on my questions? Then we can see what needs to be changed in the PR :)

Thanks again and have a nice day

2021-06-19 22:43 UTC, kusigit commented
Hello @yeldiRium

Thanks for the review. You are absolutely right about your comments. I changed the type for the `encryptConnection`. In most cases the four properties should be enough. Let me know if you think we should support them all.

Greetings

2021-06-21 10:21 UTC, yeldiRium commented
Thanks for the update, @kusigit :)

I made some changes as well.

- I adjusted the CLI options a bit. The interface for the options must only contain the primitive base types the CLI framework can handle, so we can't use the `ConnectionOptions` interface there. We have to parse and validate the incoming string.
- I also added some tests that the option is parsed correctly and that connecting to a database via SSL works.

I dislike putting certificate files into a repository, but in this case it's only self-signed certs for the tests and their validity is ignored, so it should be fine.

@goloroden do you want to do a final review?

2021-07-11 20:02 UTC, goloroden commented
@kusigit @yeldiRium Sorry for the very late reply – I've cleaned up lots of PRs this evening, and I'll come to this tomorrow 😊

2021-07-14 10:15 UTC, goloroden requested changes
@yeldiRium Sorry that it took me that long to finally review the PR. Overall, it looks good, however, I have left a few comments on minor things that caught my eye.

Could you please have a look at them?

2021-07-14 10:15 UTC, goloroden commented on lib/stores/consumerProgressStore/Postgres/PostgresConsumerProgressStoreOptions.ts
> +  encryptConnection?: boolean | ConnectionOptions;
Is this actually `boolean | …`, or shouldn't it rather be `false | …`?

2021-07-14 10:15 UTC, goloroden commented on lib/common/schemas/getConnectionOptionsSchema.ts
> +          cert: { type: 'string' }
Should we maybe rename this to `privateKey` and `certificate`, to make it more readable?

2021-07-14 10:15 UTC, goloroden commented on lib/common/schemas/getConnectionOptionsSchema.ts
> +        additionalProperties: false
The `required` field is missing here (and I think we should even add it if nothing is mandatory, just to point out that we did not forget to add `required` 😉 ).

2021-07-14 10:15 UTC, goloroden commented on docker/wolkenkit-postgres-ssl/server.req
> +Certificate Request:
I don't think that we need to keep the CSR, do we?

2021-07-14 10:15 UTC, goloroden commented on docker/wolkenkit-postgres-ssl/server.key
> +-----BEGIN RSA PRIVATE KEY-----
To be in line with other places where we use certificates, this should rather be `privateKey.pem`.

2021-07-14 10:15 UTC, goloroden commented on docker/wolkenkit-postgres-ssl/server.crt
> +Certificate:
To be in line with other places where we use certificates, this should rather be `certificate.pem`.

2021-07-14 10:15 UTC, goloroden commented on docker/wolkenkit-postgres-ssl/privkey.pem
> +-----BEGIN ENCRYPTED PRIVATE KEY-----
What's the difference between this private key and the other one?

2021-07-14 10:15 UTC, goloroden commented on lib/stores/domainEventStore/Postgres/PostgresDomainEventStoreOptions.ts
> +  encryptConnection?: boolean | ConnectionOptions;
Same question as above 😉

2021-07-14 10:15 UTC, goloroden commented on lib/stores/lockStore/Postgres/PostgresLockStoreOptions.ts
> +  encryptConnection?: boolean | ConnectionOptions;
Once again 😉

2021-07-14 10:15 UTC, goloroden commented on lib/stores/priorityQueueStore/Postgres/PostgresPriorityQueueStoreOptions.ts
> +  encryptConnection?: boolean | ConnectionOptions;
And another one 😉

2021-07-14 10:15 UTC, goloroden commented on docker/wolkenkit-postgres-ssl/Dockerfile
> +FROM postgres:13.3-alpine
We also need to add this `Dockerfile` to the dependabot configuration.

2021-07-20 14:14 UTC, yeldiRium commented on lib/stores/consumerProgressStore/Postgres/PostgresConsumerProgressStoreOptions.ts
> +  encryptConnection?: boolean | ConnectionOptions;
Yes, it is `boolean | ConnectionOptions`. This stems from [@types/pg/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cc94a59c9f4244b50b6cc46acad46f75fd10aec7/types/pg/index.d.ts#L27).

2021-07-20 14:16 UTC, yeldiRium commented on lib/common/schemas/getConnectionOptionsSchema.ts
> +          cert: { type: 'string' }
In principle I agree, but we re-use the `ConnectionOptions` type from the Node.js core module `tls`, and these are the terms that module uses. We could instead define our own options and transform them internally to the options `tls` wants, but I think in the context of a database store configuration it is okay to stick with the technical terms used by the database adapter.

2021-07-20 14:18 UTC, yeldiRium commented on docker/wolkenkit-postgres-ssl/privkey.pem
> +-----BEGIN ENCRYPTED PRIVATE KEY-----
I think none and this one is unused anyway. I'll remove it.

2021-07-22 05:32 UTC, goloroden commented on lib/common/schemas/getConnectionOptionsSchema.ts
> +          cert: { type: 'string' }
I think I'd actually prefer the option to have our own options and transform them, first, because IMHO `privateKey` and `certificate` read more nicely than `key` and `cert`, and second, because this way we decouple our public interface from the technical internals of Node.js.

I know, it's not very probably, but if they change their naming, we would either stick with those names (which still do not read that nicely then), or we would adjust ours as well as a breaking change – in the end, because an internal dependency has a breaking change.

What do you think on this?

2021-07-22 05:35 UTC, yeldiRium commented on lib/common/schemas/getConnectionOptionsSchema.ts
> +          cert: { type: 'string' }
These are valid point and I think you're right that it's a good idea to decouple from node's internals. I'll do that.

2021-07-22 05:40 UTC, goloroden commented on lib/common/schemas/getConnectionOptionsSchema.ts
> +          cert: { type: 'string' }
😊

2021-08-05 10:08 UTC, goloroden approved these changes

2021-08-05 10:09 UTC, merged